### ISSUE TITLE
Solar Power - and beyond

### ISSUE THREAD

**Issue by typxxi** [isotopp/isotopp.github.io#141]
https://blog.koehntopp.info/2022/05/02/a-solar-roof.html

Ich schreib mal auf deutsch. Großer Speicher heißt nicht immer gut, weil der LFP Akku eh über kalendarische Alterung stirbt und nicht in Folge der Zyklen, die bei 3500 bis 6000 Zyklen liegen, was bei Dir im Idealfall hieße, Du schaffst so 200 Zyklen und damit 17 bis 30 Jahre.

200 ist schon viel, denn durch die Ost Westteilung und Verschattungen wird das im Winter eh recht schwierig, weil nicht genug hineinkommen wird, da die PV zu klein ist und eine 15 kWh Batterie zu groß bei dem aktuellen Lastprofil von 2022. Ich bezweifel, dass Du überhaupt 200 Zyklen bei der 15 kWh voll kriegen wirst, weil Dein Nachtverbrauch im Sommer gering ausfällt  - wegen der Kürze der Nacht und dann nur noch die Übergangs Jahreszeiten mit längeren Nächten und guten Sonnenerträgen blieben, wo Du bei 5500 kWh und damit grob 15 kWh / Tag landest, was für die Nacht ja aber kaum 50% = 7,5 kWh bedeuten wird, sondern sagen wir in 6h das Haus auf Grundlast zurückfällt, die Du am besten beim nächsten Familienurlaub ermittelst durch Zählerstand notieren bei Haus verlassen und bei Rückkehr, ich meine wirklich aufschreiben und nicht nachher schätzen, wann das wohl so war. 
Der Verbrauch in der Zeit, den Stunden Eurer Abwesenheit ergibt Deine Grundlast (elektrisch nicht ganz korrekt, weil zyklische Verbraucher wie vor allem Kühlgeräte mit gezählt werden, obschon per Defintion zyklische Verbraucher kein Teil der Grundlast sind. In diesem Fall aber schon, wenn Du an die Zyklen für den Akku per Überschlag kommen willst, vor allem auch, um den Verbrauchern durch Messen / rechnen mal auf die Spur zu kommen, weil dort das größte Potential liegt. Da reicht es nicht, den Server mit 100W zu schätzen, sondern zu messen und um jedes Watt zu kämpfen (wobei in NL vielleicht nicht, solange jede PV kWh 91% oder 82% oder 73% Wert behält), weil dann auch der Kampf beginnt um jeden einzelnen eurer Stromsauger, den  247  Verbrauchern wie einer Fritzbox mit 11 W oder deren Repeater , die gern wie viel schlucken mag: 10 W und mehr 

Daumenregel: 1 W Verbrauch im 247 Betrieb = 9 kWh p.a.
Eselsbrücke für viele / männlich:  um von Watt zu kWh p.a. braucht es eine 8,8, also die große 8,8 Kanone

Warum ? : 1 Watt x 24 h / Tag x 365 Tage / 1000 = 8,76 kWh
oder einfacher: weil 1 Jahr = 8760 Stunden und in kWh eben eine 8,8 reicht

Der Server kostet dann fix 880 kWh / a und da sollte eine Menge zu sparen sein durch die passende Energiespar Plattform, denn gerade da kam ja auch der Erfolg des Raspi her. Ein Raspi 4 liegt grob 4 W als unterem Ende, also 96 W Einsparung, nur kann da ja auch ein Fileserver Rack dran hängen, so dass andere Kaliber Sinn machen, nur ist das der 1. Punkt, Strom zu sparen. 
Zum Raspi Verbrauch hier ein guter Beitrag , der die verschiedenen Lastsituation betrachtete
https://buyzero.de/blogs/news/was-kostet-mich-der-pi-4-an-strom-im-jahr-how-much-does-power-usage-cost-for-the-pi-4, 

OK, zuerst bei Verbrauch schauen und sparen, gibt lächerliche Dinge, aber sie bringen was, natürlich in Deutschland mehr als in NL, weil hier die kWh eingespeist mit 8 cent vergütet wird und aktuell so 35 Cent kostet, wenn sie in der Nacht gebraucht wird. 
Daher ist der Druck hier größer, Strom zu sparen.

Wer Alexa in Form von Echo Show & Co hat, der kann sich fragen, ob er 1. die Helligkeit braucht, mit der die rennt oder es mit weniger auch geht. 3 Watt sind nirgendwo fixer gespart als da. 
Und noch viel mehr, wenn man die Frage der Helligkeit richtig zu Ende denkt für sich: Display ist immer aus, außer es schallt "Alexa"
Die Einstellung gibt es tatsächlich, den Nachtmodus, den wir auf 12:00 bis 11:59 gesetzt haben, so dass der Echs show 1x pro Tag mittags erwacht und Lebenszeichen von sicht gibt. Schont das Display (unser 1. Show mit 5 Zoll hat ein leidendes Display) und spart so grob 6 Watt, wenn ich mich recht entsinne: 54 kWh p.a. bzw. 18€  

Und die Kids lernen das nur so, was wir selber in der Jugend nie lernten, denn Wasser und Strom flossen ja immer gut und reichlich und nur die Eltern hatten 1x im Jahr Kopfschmerzen, woher nur dieser Anstieg stammte. 

OK, zurück zur Batterie. Ich gehe von sagen wir 220 W Grundlast aus, dann hast Du vereinfacht in 6 Monaten eine Dunkelphase mit 7 h Kernnacht und 3h Abendprogramm, wo die Batterie liefern darf. 7h x 220 W + 3h x 750W (das ist schon eher viel für TV schauen 120 W bei 65" mit Sky Receiver & Licht an + 50" Monitor & Laptop an = 90W  ) = 1540 + 2250 =3790 Wh ~ 4 kWh pro Nacht in den 6 Monaten, im Sommer aber auch weniger, weil die Sonne eher und länger Strom liefern kann, die Batteriephasen kürzer ausfallen.

Kontrollrechnung: die übrigen 14h x 750 W ergäben 10,5 kWh und damit Tagesverbrauch 15 kWh.

OK, damit sollte klar sein, dass die 15 kWh Batterie zu groß sein dürfte, außer die Dinge ändern sich wie angedeutet. 
Fangen wir mal damit an, dass Du einen gleitenden Übergang bei der Heizung siehst, dann gäbe es da als 1. Weg die Nachrüstung einer Split Klimaanlage als Heizung für die großen Räume vor allem im EG, wofür Du selber nicht viel Geschick brauchst, weil es nur 1 Kernbohrung braucht und danach nur noch Kabel verbinden und Maulschlüssel nutzen, ggf. mit Drehmomentschlüssel. Die Anlage kann dann heizen und im Sommer kühlen, was alle südeuropäischen Länder seit Jahren nutzen, weil deren Heizlast geringer ist und der Wirkungsgrad sehr hoch, weil aus der Außenluft die Energie gezogen und direkt nebenan im Raum abgegeben wird ohne 20m Heizungsleitungen und Verluste. Wir haben 5,4 kWh große Mitsubishi nachgerüstet - im Altbau der 70er, der aber schon damals mit über 10 cm Wand und Decke gedämmt war.  Die kosten Dich inkl. WLAN und aller Quick Connect Leitungen gut 1100€ - wenn Du hier jemanden beauftragst, dann sind es 3000€, so dass Du siehst, wie sehr sich da das lohnt. Nimm aber eine Marke, in der Regel reicht aber das Basisgerät, denn Du kannst da viel Geld in Design investieren mit begrenztem Nutzen, denn für 500€ mehr bekommst Du die gleiche Anlage, die aber per Fernbedienung den Luftstrom nicht nur vertikal , sondern auch seitlich lenken kann. Wer das braucht, bitte, aber 1600€ heben die Hemmschwelle, so etwas mal zu probieren. Und: große Räume eignen sich besser, weil 1. Wärme aufsteigt und die Anlagenkosten sich nicht linear verteilen, also kleinere 2,2 kW Anlage für 40% zu haben ist. Die kostet dann 800€ statt 1100€, macht also kaum Sinn. Von daher Split Klima immer größer auslegen als der Heizbedarf wäre, weil Du immer noch mit Tür auf das Haus als solches mitwärmen kannst, besonders bei Euren wohl vielen Etagen. Na klar, für 500€ mehr bekommst Du auch noch einen kleinen Bonus bei der Effizienz, denn statt COP 4,1 gibt es dann vielleicht 4,4 - also 1 kWh elektrisch rein bringt 4,1 oder 4,4 kWh Wärme.  Brauchst aber lange, um mit der 10% höheren Effizienz die 500€ reinzuholen, da hast Du mehr von vielen kleinere Anlagen. Bei Multisplit Anlagen muss man wissen, dass Du da auch 2 oder 3 Innenräume heizen kannst, wobei jeweils 2 oder 3 Innengeräte an 1 Außengerät angeschlossen werden. Funktioniert gut, kostet aber auch und hat Schwächen, wenn ein Raum kalt und der andere auf Vollgas / Vollstrom laufen soll. Mag sich bei benachbarten Räumen lohnen. Bei Quickconnect musst Du wissen, dass sich das Kühlmittel im Außengerät befindet. Mit der Quickconnect Leitung kannst Du die beiden Geräteteile selber verbinden und in Betrieb nehmen - außer Du lebst in Deutschland, da brauchst Du den Klimaschein, aber in Italien war das für uns nicht der Fall. Es muss Dank Quickconnect kein Vakkuum erzeugt oder kontrolliert werden, solange Du mit 7 m Rohrlänge klar kommst, denn für 7m packt Mitsubisih Kältemittel in das Außengerät. Ansonsten muss der Klimatechniker kommen und nachfüllen. 
Lange Vorgeschichte, um zu zeigen, dass man auch elektrisch zuheizen kann oder gar mit 3 Anlagen a 5,4 kW den alten Heizkessel an Heizleistung mit 16 kW erreichen kann. An den sehr kalten Tagen, die Du an 2 Händen zählen kannst, wenn es unter 5°C geht, verliert die WP ihren Wirkungsgrad und Arbeitsleistung, da sollte dann was helfen ? Gas heizen und mit elektrischem Heizlüfter.

Das alles nur, um zu sagen, dass diese Heizung sinnvoll sein kann und dann auch teils von Batteriestrom profitieren kann, also in der Übergangszeit dann, wenn morgens die Sonne noch weg ist oder abends schon wieder. Nur braucht eine 5,4 kW Heizung mit COP 4 was an Strom maximal ? 1,6 kW - wenn Du bei 12 ° heim kommst und das Ding auf 28° drehst und mit voller Drehzahl Wärme brauchst. Die 1,6 kW machen es Dir auch leicht, dieses Gerät nachträglich an eine normale UNterputzdose in den Stromkreis einzubinden. Damit will ich sagen, dass hier eine 5,4 kW   Anlage im Winter einen Wohnraum konstant auf 23°C hielt und dabei 4 kWh am Tag gebraucht hat, in der Übergangszeit also weniger (2 bis 3 kWh), was wichtig ist, weil da ja dann der Akku auch voll sein sollte und damit die Frage kommt, ob der Akku die Nachtzeit versorgen kann. Von den 2 bis 3 kWh entfallen dann vielleicht 40% auf die Nacht oder weniger, wenn man Nachtabsenkung der Temperatur in Kauf nimmt, was hier wegen Senioren im Haus nicht (mehr) geht. 
Nimm einfach mal 1,3 kWh für die Nacht je Gerät und schwups bist Du bei 3 Geräten bei 4 kWh. 
Mit den 4 kWh Alltagsverbrauch und mit 4 kWh fürs Heizen per Split Klima in 3 Räumen und mehr landest Du bei 8 kWh Bedarf und irgendwie ist der 15 kWh Akku immer noch verdammt groß, liegen also 3600€ Kapital brach herum. 
Daher der Rat, das ganze mal mit 10 kWh zu denken, die Dir vielleicht 2400€ sparen, die reichen, um dafür Splitklima zu kaufen.

Jetzt mag noch die Frage kommen, wie es mit dem warmen Wasser wäre. Genau, das ist dann auch so eine noch einfachere Sache. 
Es gibt vor allen in Südeuropa Monoblockanlagen, die meist in einem wärmeren Raum aufgestellt werden wie Heizungskeller und dort aus der Umluft die Wärme ziehen und in ihren 100 Liter Wasserbehälter speisen. Diese werden an nur 2 Rohren in den bestehen Warmwasserkreislauf eingebunden, was Du auch selber machen kannst. Keine weitere Veränderung erforderlich, alles beim Alten. Du bekommst ein ca.. 50 x 50 cm Objekt was ca 120 cm hoch ist und meist an die Wand gehängt wird, in Südeuropa auch gern in die Küche, so dass die Anbieter aus Südeuropa das auch gern mal wie ein Interieur Möbel gestalten , schönere Oberfläche und Bedienung als die typischen Heizungen. Kostet was ? Ab 900 bis 1100€  von Ariston in der einfachsten Variante - ich rate Dir aber sofort, da genau zu schauen, denn die kommen ohne WLAN und SMART, haben mitunter aber eine Steuerleitung, so dass Du bei PV Überschuss eben auch das Wasser warm machen kannst. Lohnt sich alles für NL heute nicht so sehr , aber mit jedem Jahr weiter un 9% weniger Wert der eingespeisten kWh um so eher und mehr. 
Nun nimmst Du einfach hat , Du hast da 100 Liter, die mit 15°C reinkommen und auf 55°C erwärmt werden müssen. 40°C x 1,1 Wh / °C und 100 Liter enden bei Wärmebedarf von 4400 Wh  , wobei so eine Ariston Nuos Primo mit COP 3 als Wirkungsgrad kommt. Das bedeutet, Du brauchst 1,5 kWh. Ist die Frage aber, wie viel kWh Du morgens brauchst, bevor die Sonne aufgeht, um den Behälter aufzuheizen. Da sind die 40°C ja selten fällig, weil nicht immer abends noch geduscht worden ist und 100 Liter 15° Wasser nachrauschten, sondern Du mit sagen wir 100 Liter 40°C warmen Wasser aus der Nacht kommst und dann nur noch 1/3 der Heizlast hättest, eben 15°C erwärmen statt 40 °C, womit es nur noch 0,600 kWh wären. Und damit ist 3/4 des Jahres, wenn im Akku auch Strom sein wird, der Akku mit 9 kWh ausgelastet, im Sommer noch weniger, im Spätherbst und frühen Frühling mehr. 

Ach ja, der Elektroflitzer soll ja auch eher tagsüber geladen werden als mit Verlusten aus der Batterie in die Batterie, so dass man dessen Bedarf als Ausnahmen vergessen kann. Er ist im Übrigen die viel billigere Batterie, stell Dir mal einen 50 kWh PKW vor, der aus den HUAWEI 15 kWh Speichern gebaut würde, denn dann wären das schon 25000€ , also ist der günstigste Speicher Dein auto und selbst in Deutschland wird Vehicle 2 Load als rückspeisen ins Haus bzw. als Vehicle 2 grid ins Netz kommen u.a. und zu allererst VW, die sich gegen die Stromlobby durchsetzten. Von daher bau den Akku nicht zu groß, wenn in 1 Jahr VW und dann andere Vehicle 2 Load Fahrzeuge liefern (Ford F150 Lightning Truck kann ein ganzes Haus versorgen, weil ich mein bis 9 kW aus dem Fahrzeug gehen können, wobei klares Negativbeispiel). Ein MG4 in Golf Größe kommt in der Basis mit einer 51 kWh LFP battery und einer 2,3 kW Leistung Vehicle 2 Load (kein 2 Grid) . Dem MG4 Akku mit 3500 Zyklen und mehr ( 300 km WLTP hieße bei 3500 Zyklen aber eine Akkulebensdauer von 1.250.000 km, die das AUto nie fahren wird, also der Akku länger hält als das Auto mechanisch) kann dann die Hausbatterie ersetzen, noch ein Grund mehr, eine NICHT ZU GROSSE HAUSBATTERIE zu kaufen. 

Nun der Punkt, der ebenso wichtig ist: Wenn Überschuss, dann bestimmte Verbraucher mit Überschuss Strom betreiben

Das nennt sich bei Auto und Wallbox Überschuss laden, die Softwarelösung heißt wohl EVCC, wenn Du nicht eine teure Wechselrichterhersteller gebundene Lösung kaufst. Nur läuft die dann meist nur mit einer Huawei Wallbox, so es die gibt, der nächste Verbraucher wäre ein Problem, von daher schau Dir EVCC an, die einen Raspi braucht oder einen SonOff ihost, der ein lokales Smarthome ohne China Cloud für aktuell noch heute 55€ bietet, also eine grob Pi 3 / Pi 4 vergleichbare Leistung mit einer Docker Einbindung und Zigbee, WLAN und BT an Bord, sowie anderem Zeug. Heute noch im Release Angebot, was seit März gelaufen ist. Ansonsten wohl etwas teurer, aber günstiger als Pi 4 neu von ebay. 
EVCC erlaubt Dir das Laden von 1 oder mehreren Fahrzeugen bzw. Verbrauchern mit Regeln wie lade nur das, was an Überschussstrom sonst ins Netz ginge (die Fahrzeuge können meist erst ab 6A) und das auch intelligent, denn neben dem reinen grünen Überschuss gibt es noch andere Ladeprogramme, um die Karre schnell zu laden auch mit Strom vom Netz. 
Und Deine Splitklima, ggf. aber auf alle Fälle die Warmwasser Wärmepumpe sind ein Super Überschussverbraucher in der Zukunft und auch in NL, wenn die eingespeiste kWh immer weniger wert wird, denn besser aus 1 kWh Strom 3 kWh Wärme im Wasser erzeugen als nach 5 Jahren nur noch 55% der eingespeisten kWh zurückzubekommen. 

Dieser Energymaster ist die Zentrale, denn nur diese Überschussverbraucher lassen sich wirklich gut mit Überschuss betreiben. Eine Spülmaschine oder Waschmaschine nur und erst dann ein zuschalten, wenn der Strom reicht, ist im Alltag eher ein Alptraum in der Steuerung und muss man bzw. alle in der Familie wollen. Abends nach Haus und die Maschine ist nicht gelaufen, da kippt die Stimmung dann fix. Von daher schau mal EVCC an, ist opensource und bestimmte Funktionen brauchen eine Sponsor, was der Wallbox Hersteller übernommen haben kann, so dass alle Produkte des Herstellers das gratis können - oder kostet Dich maximal 2$ p.a. und ist OpenSource made in Germany mit sehr lebendiger Community, ich meine evcc.io ist die Site.

War es das ?

All das ist die alte, händische Art so was anzudenken und zu durchplanen, hätte Dir vor 1 Jahr vielleicht auch mehr geholfen, das so zu finden, aber sei es drum, da auf dem Blog nix neues stand, sah es erst einmal nach dem Stand der Dinge aus, wo sich ein Akku kaum rentiert, wenn man von 1 kWh eingespeist morgen  oder im Dezember noch 0,91 kWh zurück bekommt.  
Von daher mag das jetzt Sinn machen und Dich auch schon länger fragen lassen, was noch geht und wie in welcher Reihenfolge, nur der Rat, dass Du lieber einen eng bemessenen HAusakku kaufst und im Hinterkopf hast, dass die PKW das künftig von Haus mitbringen werden und zwar vor 2030, denn VW ist ein Big Player wie ein F150 Lightning in den USA bei Trucks. 

All das hier ist die alte , einfache Art, weil jeder der Dein Blog dazu liest, dem auch folgen kann. 
Willst Du mehr und genauer, also auch PV Anlage planen und vergleichen können, dann kannst Du sozusagen Dein Haus an Deinem Ort einfach in 3 D planen und Deine Anlage, wie sie ist, nachbauen und passend dazu Deine Verbrauchsprofile hinterlegen, wann welcher Verbraucher am Tag oder in der Woche läuft und was an Strom braucht oder aber Du nimmst die 5500 kWh und lässt die für einen 3 Personenhaushalt mit 1 auf Achse und der Rest zu HAus runterbrechen. 

Diese Software errechnet dann auf Basis der Einstrahlungsdaten an Deinem Ort die Erträge je Minute aus der PV und stellt dem ggü. die Verbräuche , so dass das System für jede Minute eine Bilanz erstellt und das ganze zu einem JAhresergebnis. Da kannst Du dann alternative Module simulieren, alternativ Belegungen und Wechselrichter, ebenso Batteriegrößen, DIY Akkus und die Wärmepumpe bzw. Dein Auto elektrisch fahren lassen mit wöchentlich 500 km und ladeprofilen und Zeiten.

Das findest Du auf bei  Valentin Software in Berlin - gratis als 30 Tage Demo, wobei Du die Kundenprofi Auswertungen halt nicht drucken kannst, aber mit Screenshot kriegst Du alles auch so. Klar, die 30 Tage schreien nach VM Installation - oder aber Du nutzt einfach das, was geboten wird: 30 Tage Demo gratis 
Für die meisten bedeutet das, nach 30 Tagen ist die Zeit dann rum, die Planerei fertig. Klar, und wenn man länger braucht, eine VM Installation oder neue Maschine nehmen und dort weiter machen. 
Bequemer ist aber , wenn man das Hirn benutzt und der Hersteller hält , was er verspricht, also Fair Use. Da es so 7 bis8 mal im Jahr eine neue Version gibt, kannst Du auch starten und in 2 Monaten die neue Version x.3 installieren wie ein Update und Du bist willkommen für weitere 30 Tage, bis die Sperre eintreten wird. Ganz smart fängst Du einfach mal an mit der Version aus Januar 2021 , denn dann hast Du bis Mai 2023 schon 15 bis 20  Versionen im Vorlauf und kannst 15 bis 20 Monate auf derselben Maschine planen. 
Alle Versionen gibt es dort zum Download und laufen prima. 
Der Anbieter hat auch alle Daten der Module und Wechselrichter hinterlegt, Du sparst Dir das fehlerträchtige Abtippen der Specs, die das System braucht, um zu simulieren. Du mussst nur Modul Daten etc. auswählen und dann sollte das System signalisiern, dass alle Komponenten passen oder woran es scheitert. 
Das Ergebnis der Simulation ist super, die Daten sind realistisch, also die Planung zuverlässig, die Modul, Batterie, Wechselrichterdaten werden teils von den Herstellern eingepflegt und lfd. aktualisiert, weshalb alles von deren Servern zur Laufzeit kommt. Ist dann Dein WR dabei mit neuen Specs oder verbesserter Version , dann wirst Du gefragt, mit welchem Modell Du weiter arbeiten willst. 
So weit so gut.

Die Planung selber ist da schon was anderes, man braucht, um sich da einzufinden, aber am Ende geht es oder Du kennst Leute und kannst fragen. Von daher halt der Hinweis, dass Du PV SOL in der PREMIUM Version, nimm nicht die kleineren, sondern gleich das Profi Tool, sehr gut nutzen kannst, um Dein System von heute zukunftssicher zu gestalten durch u.a. Simulation. 

Lange Geschichte, aber ich denke, dass Du was daraus machen wirst, so oder so Dich zum Denken anstoßen wird und das ggf. dann auch wieder ein internationales Publikum erreichen kann. Ach ja, ich verkaufe nix, also keine Wärmepumpe, PV , Module oder Wechselrichter, aber ich weiß schon, wo Du privat aktuell die günstigsten Module in und um Deutschland kaufen kannst, wie Du bei der Unterkonstruktion auf dem Dach mal eben 40% ggü. deutschen Preisen sparen kannst, weil in einem Nachbarland das Zeug eben 40% günstiger ist. Bei 2000€ sind 800€ fix gespart. Such mal ein Modul mit über 500 Wp für weniger als 170€ - dann suchst Du lange.
All das brauchst Du aber nicht, weil Du hast schon fast alles - außer Du wolltest vergrößern, denn das könnte der Fall sein, je mehr elektrisch laufen wird , also nach Splitklima und Warmwasser WP vielleicht auch weitere Autos, gar die alte Heizung ablösen. 
Dazu hast Du noch bedingte Reserveflächen, die auf den Garagen / Carport  etc. Je weniger die eingespeiste kWh wert sein wird, je eher wirst Du mehr Leistung auf dem Dach haben wollen und von daher hast Du jetzt Zeit, die Zukunft so zu planen, dass Du Dir ad hoc auch nix verbaust wie mit einem teuren, zu großen Speicher , denn: im Winter wirst Du den ausschalten, weil ein Hybrid Wechselrichter dann auch fix 70 oder über 120 Watt in der Nacht jede Stunde aus der Batterie ziehen kann , um nur bereit zu sein, Strom zu erzeugen. Jetzt passiert nix dergleichen, denn die PV Module liefern keinen Strom und Dein Wechselrichter legt sich schlafen. Kommt die Batterie, dann will der aber 247 seinen Anteil zum Betrieb und der kann hoch sein, höher als Dir lieb ist, weshalb dann viele gerade mit so einer eingeschränkten Ost -Westleistung wie bei Dir eben die Kiste im Winter aussschalten, weil der Überschuss zum Laden zu gering sein wird. Daran denken die wenigsten udn fallen nachher aus allen Wolken, wenn die Monatsauswertungen plötzlich hohe Verluste zeigen wie 200 kWh für den Betrieb des Akkus im Monat, weil ja der Verbrauch des WR nur durch den Akku provoziert wird. Ohne Akku wären die nicht da.  
 
Gutes Studium und Gelingen - ich schau mal bei Gelegenheit vorbei und wenn Fragen sind, dann kann ich vielleicht mit Antworten helfen oder sagen, wo Du die Antworten findest. Klar, das macht alles heute noch nicht wirklich Sinn in NL, weil eben 91% oder 82% jeder eingespeisten kWh gratis zurückkommen , wann immer Du die im Jahr brauchen könntest, aber mit jedem Jahr weiter kommst Du deutschen Verhältnissen näher, wo eben die kWh vom Netz das 4,x fache dessen kostet, was Deine eben eingespeiste kWh bringt, von daher endet das in derselben Richtung früher oder später.

**Comment by isotopp** [comment]
Ich komme leider erst jetzt dazu, Deinen Text hier zu bearbeiten.
Ich habe ihn als http://blog.koehntopp.info/2022/05/02/a-solar-roof-2.html#steuerung-und-modellierung aufbereitet, ein wenig geglättet, aber inhaltlich und zu weiten Teilen auch sprachlich zu gelassen und Dich attributiert.

Der Text wird gerade gerendert, und sollte gleich online gehen.
