### ISSUE TITLE
"Tags" links are 404s

### ISSUE THREAD

**Issue by fghaas** [isotopp/isotopp.github.io#152]
At the bottom of each page (example: https://blog.koehntopp.info/2022/05/02/a-solar-roof-2.html) there is a list of "tags" links. Those are subtly broken ­— for example, the `energy` tag button on the aforementioned page links to <https://blog.koehntopp.info/%20tags/#energy> whereas the correct link is <https://blog.koehntopp.info/tags/#energy>.

I suppose there's superfluous whitespace in some bit of configuration somewhere. :)

**Comment by isotopp** [comment]
Thanks for finding that. This commit should be fixing the issue. The site is being rendered and the updated content should be available in approximately 10m.

**Comment by fghaas** [comment]
Yes, looks much better now — thank you!
