### ISSUE TITLE
Table of Contents wird beschnitten abhängig von horizontalem Viewport/Auflösung/Zoom

### ISSUE THREAD

**Issue by Syphdias** [isotopp/isotopp.github.io#154]
Beim Artikel https://blog.koehntopp.info/2023/08/28/der-admin-beruf.html ist mir aufgefallen, dass die ToC nicht komplett sichtbar ist. Ausgelöst habe ich das durch heranzoomen, aber das passiert auch auf dem Handy.

![image](https://github.com/isotopp/isotopp.github.io/assets/16988672/852f1f8d-44be-4c98-9bee-65cec7e23778)
![image](https://github.com/isotopp/isotopp.github.io/assets/16988672/36410c72-d321-41c4-8eb4-a5634447dfad)

Das scheint daher zu kommen, dass hier der Tag `header` verwendet wird, der auch für das Bild über dem Artikel wird und die Höhe auf 25% der Viewport-Höhe beschränkt wird. (Sofern ich `hv` hier richtig verstehe.)
```css
header, header img {
    max-height: 25vh;
}
```

Ich würde vermutlich einfach einen `div`-Tag verwenden, aber ich weiß nicht, was das in HTML für Nebenwirkungen hat. Dafür habe ich nicht genug Web-Foo. Vielleicht ist der `header`-Tag wichtig für den Reader-Mode, o.Ä. Man könnte natürlich auch das Styling des Bildes an eine Klasse hängen, damit es nicht auf alle `header`-Elemente wirkt. Dunno.

**Comment by isotopp** [comment]
Guter Hinweis. Mir war das neulich schon aufgefallen, aber ich hatte noch keine Zeit, das zu untersuchen.

Mit Deinem vh-Hinweis kann ich gezielter suchen.

**Comment by Syphdias** [comment]
Na, dann hat es ja was gebracht. Sieht gut aus!
