### ISSUE TITLE
Restic: Backup vor Prune

### ISSUE THREAD

**Issue by bebehei** [isotopp/isotopp.github.io#158]
Habe gerade deinen ausführlichen restic-Artikel gelesen.

Danke, war wieder sehr erfrischend.

Warum machst du prune vor dem eigentlichen backup und nicht andersherum?

**Comment by isotopp** [comment]
Ich habe zu jeden gegebenen Zeitpunkt mehr als 50 Snapshots in der Historie, es macht kaum einen Unterschied.

Aber mit dem `prune` vorneweg bekomme ich zuerst Plattenplatz zurück, und ich bekomme diese Statistik in der Cron-Mail zuerst, was genau ist, was ich brauche.

**Comment by bebehei** [comment]
Danke!
