### ISSUE TITLE
Wie ChatGPT funktioniert -  Bi-, Tri- und n-Gramme

### ISSUE THREAD

**Issue by Sweepi** [isotopp/isotopp.github.io#166]
Hi,

ich kann dem Text ab Zeile 71 nicht folgen:

> Nimmt man mehr Kontext, also statt Paaren Dreiergruppen (Tri-Gramme) oder noch längere Gruppen, dann bekommt man irgendwann fast aussprechbare oder reale englische Worte. Schon 4-Gramme produzieren gute Worte. Englisch hat also einen Buchstabenkontext von circa 4-5.

>Image

> _Eine Reihe von Worten, die aus Nachfolgewahrscheinlichkeiten von Bi-, Tri- und n-Grammen erzeugt worden ist. Ab einer Länge von etwa 4 entstehen oft gültige Worte der englischen Sprache._

Beispiel Bi-Gramm: "qu", "on"
Beispiel Tri-Gramm: "was", "hia"
Aber was will mir das Bild sagen? in der ersten Spalte 0(!) - 5, in der 2 Spalte wortsalat, wobei sich die unteren Zeilen mehr der Englischen Sprache annähern.
Was soll ein 0-Gramm sein?
Was soll ein 1-Gramm sein? Die Häufigkeit der einzelnen Buchstaben?
Oder heist "3" in der ersten Spalte, die zweite Spalte der gleichen Reihe besteht aus jeweils 3 Bi-/Tri/n-Grammen?
Was soll dann 0 heissen? Und: Heist das: "timumumoi" ist ein real vorkommendes 9-Gram?
Werden bei der Paarbildung Satz- und Leerzeichen ignoriert?

Fehlt hier etwas / verstehe ich den Gedankengang/-sprung nicht?

Nebenschauplatz:

> *Waagrecht die ersten Buchstaben von Paaren, senkrecht die zweiten Buchstaben.
> Je roter und dunkler das Feld, umso häufiger die Kombination.
> Die Spalte "q" ist ganz weiß, mit Ausnahme der "qu"-Kombination.*

Senkrecht der Erste, waagrecht(horizontal) der zweite Buchstabe von Wortpaaren. 
Weil wie, du selbst schreibst: Die Spalte 'q' ist weiss, bis auf 'qu'. In der Reihe 'q' ist 'uq' hingegen sehr hell.

**Comment by isotopp** [comment]
Ein n-Gram ist eine gewichet zufällig gewählte Zeichenfolge, wobei die Gewichte n-Zeichengruppen entsprechen, die aus einem Ursprungstextpool ermittelt werden.

Man nimmt sich also einen großen englischen Textpool und guckt wie häufig eine bestimmte n Zeichen lange Zeichenfolge so im Schnitt ist. 

When shall we three meet again?
In thunder, lightning, or in rain?

In Trigrammen:
Ein Counter für whe, einer für hen, einer für ens, einer für nsh, einer für sha, einer für hal, einer für all ...

Am Ende nimmt man seine Counter und normiert diese.

Hat man diese Daten, kann man das generativ nutzen, indem man Zufallskombinationen mit dieser Häufigkeit ermittelt.

Bei 0-grams also komplett zufällig (ohne Textpool),
bei 1-grams nimmt man die Häufigkeiten von einzelnen Zeichen, 
bei 2-grams (Bi-grams) die Häufigkeit von Paaren und so weiter.

Du kannst das selbst probieren, indem Du nach einem "n-gram generator" suchst, den mit Beispieltexten lädst und dann guckst, was passiert.

---

Du hast Recht, ich habe die Richtungen vertauscht. Senkrecht ist 1, waagrecht ist 2. Ich korrigiere das.
