### ISSUE TITLE
`mailto:` links fehlen das `To` Feld

### ISSUE THREAD

**Issue by jman-schief** [isotopp/isotopp.github.io#167]
Hallo!

Zum Beispiel die About Seite:

`mailto:?subject=About&body=https%3a%2f%2fblog.koehntopp.info%2fabout%2f`

Und so überall.

**Comment by isotopp** [comment]
Das war durchaus Absicht. Das waren ja alles Sharing Links, um Artikel, die Du im Blog findest an andere weiter zu geben. Die Kontaktlinks sind weiter unten am Seitenfuß, und dort ist es anders aufgebaut.

Die Sharing-Links waren aber eh sinnlos. Ich habe den Block entfernt und das Ganze so vereinfacht.

https://github.com/isotopp/isotopp.github.io/commit/88351f69d3a46f781a39642042ba709c6cc3b83a
