### ISSUE TITLE
Sonos S2 Analysis 

### ISSUE THREAD

**Issue by th-h** [isotopp/isotopp.github.io#175]
>  Lokales Abspielen von Fileservern, ein lokaler Airsonic Abspielpunkt und andere lokale Dienste sind aus der Sonos Cloud nicht erreichbar und können daher nicht mehr funktionieren.

Kann ich so nicht reproduzieren. Die Einbindung einer "Musikbibliothek" (bspw. ein Netzwerkshare oder NAS) ist laut [Dokumentation](https://support.sonos.com/de-de/article/add-your-music-library-to-sonos) jedenfalls über die "nicht-mobilen" Apps für macOS oder Windows möglich; für Windows kann ich das bestätigen. Diese Bibliothek ist dann als "Quelle" auch in der mobilen App verfügbar.

Was fehlt ist offenbar die Möglichkeit des Hinzufügens in der mobilen App (deren Relaunch insgesamt die Übersichtlichkeit nicht verbessert hat).

**Comment by isotopp** [comment]
Die Desktop-Apps verwenden die alte UPNP API. Sie werden absehbar durch https://play.sonos.com ersetzt. Dann fällt die UPNP API weg. Die Mobile Apps verwenden die neue API und das Abspielen von durch Cloud nicht erreichbaren Inhalten ist dann nicht mehr vorgesehen.
