### ISSUE TITLE
hugo branch: title font in articles does not match Jekyll

### ISSUE THREAD

**Issue by isotopp** [isotopp/isotopp.github.io#50]
hugo: Segoe
jekyll: Something else

**Comment by isotopp** [comment]
cc @patdavid

**Comment by patdavid** [comment]
Question.

At the moment we are using a system native font stack (https://getbootstrap.com/docs/5.0/content/reboot/#native-font-stack).

This let's us render nicely across all devices and saves the bandwidth/roundtrip for calling a custom font.

I can certainly match the font for you no problem, but I wanted to make sure this was something you really wanted to do or if you were happy with the native stack we could leave it as is.

Entirely up to you - just let me know! :)

**Comment by isotopp** [comment]
I need to check what the type on strap does. Apparently it installs some kind of font pack, and I happen to like the fonts it installs. Certainly fuller than what I get on windows with this Segoe thing

**Comment by isotopp** [comment]
Fixed in #66
