### ISSUE TITLE
hugo: Search is slow

### ISSUE THREAD

**Issue by isotopp** [isotopp/isotopp.github.io#51]
Running `hugo serve -D -E -F` against localhost:1313,
http://localhost:1313/search/

Searching "for docker" in Firefox I can eventually type about 1 character every 5 seconds (Windows 10, Firefox, and as above).

**Comment by isotopp** [comment]
Seems to happen in Chrome on Windows, too, but marginally faster.

**Comment by isotopp** [comment]
cc @patdavid

**Comment by patdavid** [comment]
got it - you can assign it to me as well if you want.

**Comment by isotopp** [comment]
Merged by d28211d as part of #59

**Comment by isotopp** [comment]
Tested. Is much faster.
