### ISSUE TITLE
RSS Feeds for 2 Tags

### ISSUE THREAD

**Issue by isotopp** [isotopp/isotopp.github.io#54]
The tags `mysql` and `review` shows generate tag filtered rss feeds in `feed_mysql.xml` and `feed_review.xml`

cc @patdavid

**Comment by patdavid** [comment]
Ok, I'm looking at adding these two term RSS feeds and I have it working.  **But** I need to know if you want a full feed of every post or just the N last posts?  (Bear in mind a full feed is _heavy_ as it will be every post ever made...)

**Comment by patdavid** [comment]
I have added a parameter to config.yaml that let's you limit the feed if you want
```
rssLimit: 20
```

If you prefer no limit just remove this parameter.

**Comment by isotopp** [comment]
Limit of 20 is fine, I am not posting that much. Full feed, always :-) Checking out the code later tonight (CET)
