### ISSUE TITLE
Feed location changed (Hugo migration)

### ISSUE THREAD

**Issue by cboltz** [isotopp/isotopp.github.io#56]
The Jekyll RSS feed was located at https://isotopp.github.io/feed.xml which goes 404 now.

I could change my feedreader to Hugo's https://blog.koehntopp.info/index.xml, but - IIRC one of the migration goals was not to break well-known URLs.

So - any chance to get the old `feed.xml` URL back? (as real file or redirect, whatever is easier)

**Comment by isotopp** [comment]
The feeds are coming back, and I am aiming for the original urls

**Comment by isotopp** [comment]
Full RSS feed is now at /feed.xml.
MySQL Tag feed is now at /tags/mysql/feed.xml.
Review Tag feed is now at /tags/review/feed.xml.
In fact, all tags now have feeds.

The full feed, mysql feed and review feed are announced with meta-rel headers.

This is part of  2d6de78. Hope that solves the issue.

**Comment by patdavid** [comment]
I am looking to get the review and mysql feeds located in their old places soon.

**Comment by isotopp** [comment]
Please don't. I have informed Planet MySQL and friends of the new feed location.

**Comment by patdavid** [comment]
Ok, I assume we can close this now then?
