### ISSUE TITLE
Posts don't show a title anymore

### ISSUE THREAD

**Issue by trilader** [isotopp/isotopp.github.io#61]
From what I can see none of the blog posts have a title displayed anymore. The author information that was visible there before is also gone. They were visible in the screenshot in #53.

![Screenshot_20211108_100019](https://user-images.githubusercontent.com/1092593/140713297-93310d84-81c8-4f74-b4c6-90838100600f.png)

This is Chome 94 on Linux.

**Comment by isotopp** [comment]
Duplicate of #62, and #62 has more info.
