### ISSUE TITLE
Wide windows make the date or headline invisible.

### ISSUE THREAD

**Issue by isotopp** [isotopp/isotopp.github.io#62]
On a wide screen, the date or even the title of a post becomes invisible

![Screen Shot 2021-11-08 at 10 45 53](https://user-images.githubusercontent.com/182951/140720908-7e7ae973-baa8-47a8-80d6-eee9f5885cb6.png)
.

**Comment by isotopp** [comment]
This div should be vertically centered inside the enclosing box.

![Screen Shot 2021-11-08 at 10 46 59](https://user-images.githubusercontent.com/182951/140721078-ee257011-bfff-44c5-9fa9-1f53389d2497.png)

**Comment by patdavid** [comment]
This was centered fine on FF:
![image](https://user-images.githubusercontent.com/2778928/140775213-b3ecfd0c-f8c4-4f0d-8ec3-9154d64e5c3e.png)

I can look at what happened on chrome/ium

**Comment by isotopp** [comment]
I get the feeling that Chrome centered it vertically on the image, part of which was hidden below the line. As you make the window wider, the image gets stretched horizontally and also vertically to preserve the aspect ratio. That then made chrome pull down the headline to keep it centered on the (partly invisible) image.

**Comment by isotopp** [comment]
Properly fixed in  8823478 by @patdavid. Thanks!
