### ISSUE TITLE
Article tags not shown in article

### ISSUE THREAD

**Issue by isotopp** [isotopp/isotopp.github.io#64]
At the bottom of an article the article tags were shown in Jekyll, but aren't in Hugo.

At the bottom of an article, share tags are shown. They are nice, but not strictly necessary (if you think it improves the look).

At the very bottom, the various social icons are shown. They are good as is.

![image](https://user-images.githubusercontent.com/182951/140778398-ce48d1d1-94c1-4568-a06c-31ed89033354.png)

*Red:* Optional, not necessary. Instead or amended: List of tags from front matter.
*Green:* Keep

**Comment by patdavid** [comment]
Easy fix - let me get some things out of the way and I'll drop it right in!

**Comment by patdavid** [comment]
Addressed these in:
18e541cc6d44db2bd5d7a586443c4fb2755b9108
7b7fc6dd3a3b99a5878a2fae4a1e5b8cec9fec87
