### ISSUE TITLE
Font change does render weirdly in Chrome

### ISSUE THREAD

**Issue by isotopp** [isotopp/isotopp.github.io#67]
PR #66 enables the old Jekyll fontstack. This renders nicely in FF, but weirdly in Chrome.

Reported by @robertdahlem, Windows 10 21H1, Chrome 95.0.4638.69, Dell P2719H non-4K, can confirm on my own Windows 10 WSL setup.

Firefox:
![image](https://user-images.githubusercontent.com/182951/140882320-5fe5e888-0915-458c-89b9-1a9f59b93d5c.png)

Chrome:
![image](https://user-images.githubusercontent.com/182951/140882373-244248dd-a69a-4637-8a28-7075d02c3a02.png)

![image](https://user-images.githubusercontent.com/182951/140882425-056cda33-636e-4d08-9866-6c5f41f9c7f6.png)

**Comment by isotopp** [comment]
Problem goes away when you set Chrome to 110%

![image](https://user-images.githubusercontent.com/182951/140882579-7b377e75-bd2c-42ee-a0f9-8b8d5bdda355.png)

**Comment by isotopp** [comment]
Chrome on MacOS not affected

(Big Sur, current Chrome, 100%, non 4K Monitor)

![Screen Shot 2021-11-09 at 09 34 55](https://user-images.githubusercontent.com/182951/140890130-f0dd8bbf-e832-41fe-93ba-9a70cce12c89.png)

**Comment by patdavid** [comment]
What exactly is the problem you're seeing in that rendered text?  This feels like a chrome/windows issue with font rendering?

Ubuntu 21.04/Gnome:
![image](https://user-images.githubusercontent.com/2778928/140948740-d4d7293a-30cf-4a0e-a576-b3164cf3c327.png)

I'm looking around now to see what's going on.

**Comment by isotopp** [comment]
I will not check out the PR.

**Comment by isotopp** [comment]
After applying #68, this looks better

![image](https://user-images.githubusercontent.com/182951/140962863-e3b2f73e-c05b-4acb-bdee-b668059fbfd8.png)

And detail

![image](https://user-images.githubusercontent.com/182951/140962986-4369986e-6b2a-4636-9bc6-c0f42f8901ee.png)

This is looking very okay now.
