### ISSUE TITLE
Content Organization

### ISSUE THREAD

**Issue by patdavid** [isotopp/isotopp.github.io#72]
Something that I meant to bring up earlier but forgot was about content organiziation.

If you wanted you could also organize your posts into sub-directories and keep the assets for those posts alongside the markdown.

For example, right now you have a folder like
```
content/
├── posts
│   ├── 1997-05-14-sperrungen-im-internet.md
│   ├── 2003-08-30-fertig-gelesen-kushiel-s-dart.md
...
```

And any linked assets in the posts like images would have to go in a folder somewhere else (like in `/static/uploads/xxxx.jpg`).

Which sucks if you might have two images of the same name but different content.

You can now include the image and post markdown inside another folder using the same naming convention:

```
content/
├── posts/
│   ├── 2003-08-30-fertig-gelesen-kushiel-s-dart.md
│   └── 2021-11-10-a-test/
│       ├── 2021-11-10-a-test.md
│       └── some-image-file.jpg
```

You may not care but I was always a stickler for keeping all of the content for a post together if possible.
Anyway, something to play with if you're interested!

**Comment by isotopp** [comment]
I was under the impression that this would not work with `UglyURLS: true` enabled.

If that works, it is indeed the form I will choose for new URLs.

**Comment by isotopp** [comment]
It works. Fantastic, much cleaner.

**Comment by isotopp** [comment]
This does not work.

When adding images, the image URL in the article folder is not uglyfied, and the image is not found.

**Comment by patdavid** [comment]
Ugh, that's right.  It will actually create the directory and image, but there's not an easy way I can think of off the top of my head to reference the image gracefully.

```
content/
├── posts/
│   ├── 2003-08-30-fertig-gelesen-kushiel-s-dart.md
│   └── 2021-11-10-a-test/
│       ├── 2021-11-10-a-test.md
│       └── some-image-file.jpg
```

In this example for `2021-11-10-a-test` you would actually get this url:
`url/2021/11/10/a-test.html`

*and* a directory right next to it:
```
2021/11/13/
├── a-test
│   └── some-image-file.jpg
└── a-test.html
```

Not ideal.  Sorry for the noise! :)
